#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    Manage Database
    ~~~~~~~~~~~~~~~

    Database maintenance script.

    :copyright: (c) 2010 by the Zine Team,
                (c) 2010 by the pyClanSphere Team,
                see AUTHORS for more details.
    :license: BSD, see LICENSE for more details.
"""
# for now
import warnings
warnings.filterwarnings('ignore')

import sys
from os.path import dirname
sys.path.append(dirname(__file__))
from _init_pyClanSphere import find_instance
from pyClanSphere.upgrades import CommandLineInterface

def main():
    manage = CommandLineInterface()
    manage.run()

if __name__ == '__main__':
    main()
