#!/usr/bin/env python
"""
    Test Runner
    ~~~~~~~~~~~

    This is a wrapper script for running the pyClanSphere unittests.
    Run it with the --help option for usage information.

    :copyright: (c) 2009 - 2010 by the pyClanSphere Team,
                see AUTHORS for more details.
    :license: BSD, see LICENSE for more details.
"""
import os
import sys
sys.path.append(os.path.dirname(__file__))
from _init_pyClanSphere import find_instance
from pyClanSphere.tests import main
main()
