#!/usr/bin/env python
"""
    Test Runner
    ~~~~~~~~~~~

    This is a wrapper script for running the pyClanSphere unittests.
    Run it with the --help option for usage information.

    :copyright: (c) 2009 - 2010 by the pyClanSphere Team,
                see AUTHORS for more details.
    :license: BSD, see LICENSE for more details.
"""
import os
import sys

path = os.path.join(os.path.dirname(__file__), os.path.pardir)
os.chdir(path)
sys.path.insert(0, path)

from tests import main
main()
